### ISSUE TITLE
Width issue on the mobile version on Download page following 591dff0 / PR 155

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/FreeCAD-Homepage#180]
Following the change on the Download page, the overall width is too big on small screen mobile devices :

![FC](https://github.com/user-attachments/assets/3f68b063-f6a2-405e-8d58-8e5603a01ea1)

The text can be shortened or the wrapping improved.

**Comment by Reqrefusion** [comment]
There is a problem with the Badge class being nonwrap. Below are screenshots where I removed this from Sisyphus. However, this may not be preferred, changing the place where the badge can be placed is an option. Since I don't know which option is more suitable, I can't add it to the current revision for now.
![resim](https://github.com/user-attachments/assets/232c61ba-343a-4e91-acf3-a15ec52595db)
![resim](https://github.com/user-attachments/assets/706f9b4e-428d-4e70-96fb-19996bb6842e)

**Comment by Reqrefusion** [comment]
I found this solution more reasonable. The text showing the link is shorter.
![Screenshot 2024-08-05 at 12-44-48 FreeCAD Your own 3D parametric modeler](https://github.com/user-attachments/assets/6bfb1113-7790-4f8f-8f44-3fbbb85bb664)
![Screenshot 2024-08-05 at 12-44-30 FreeCAD Your own 3D parametric modeler](https://github.com/user-attachments/assets/f4977f11-1088-4650-a1cc-a3736649bbcf)
